### ISSUE TITLE
headless run

### ISSUE THREAD

**Issue by xrow** [hansode/packer-vagrant-templates#89]
Hi,

I was wondering, if we could run all templates with headless option. That should be more compatible.

**Comment by hansode** [comment]
Thanks for your feedback.
The reason why `headless` is `false` is for my development/debugging.
It's OK to change `headless` default value to `false`. I'll do it soon.

**Comment by hansode** [comment]
@xrow 

Changed/Fixed.
https://github.com/hansode/packer-vagrant-templates/pull/90/files
