### ISSUE TITLE
Using .jp for sourcing

### ISSUE THREAD

**Issue by xrow** [hansode/packer-vagrant-templates#92]
Hi,

I was using the mirror (http://ftp.riken.jp) from the default setup. I ran into a timeout problems since the sources of http://ftp.riken.jp where not accesable that well from from germany deu to low bandwidth. I think there is the need of replacing the mirror with mirror redirection via http://mirror.centos.org/centos-7/7.1.1503/os/x86_64/. For whatever reason the isos are not available over mirror.centos.org.

**Comment by maximd** [comment]
You got an upvote!

**Comment by hansode** [comment]
ok. will do.

**Comment by hansode** [comment]
I will do for rhel7 so far.

**Comment by hansode** [comment]
Updated for rhel7 in #101.
