### ISSUE TITLE
CentOS 7.1 new release

### ISSUE THREAD

**Issue by xrow** [hansode/packer-vagrant-templates#93]
Hi,

there had been a new release of centos 7.1 called centos 7.1-01 . The code doesn`t reflect it yet.

Instead of CentOS-7-x86_64-Minimal-1503.iso you need to use now CentOS-7-x86_64-Minimal-1503-01.iso

http://wiki.centos.org/Manuals/ReleaseNotes/CentOS7

**Comment by hansode** [comment]
https://github.com/hansode/packer-vagrant-templates/tree/master/centos-7.1.1503-x86_64

this one is for centos-7.1.

**Comment by xrow** [comment]
Yes true that one is for 7.1 but the iso is now http://ftp.riken.jp/Linux/centos/7.1.1503/isos/x86_64/CentOS-7-x86_64-Minimal-1503-01.iso and not http://ftp.riken.jp/Linux/centos/7.1.1503/isos/x86_64/CentOS-7-x86_64-Minimal-1503.iso
In centos-7.1.1503-x86_64/template.json you have the wrong url

**Comment by hansode** [comment]
ahh... i got it. i'll fix it soon.

**Comment by xrow** [comment]
Most excellent!

**Comment by hansode** [comment]
https://github.com/hansode/packer-vagrant-templates/compare/centos-7.1.1503-x86_64?expand=1

Done.
Thanks a lot.
