### ISSUE TITLE
CentOS Repos not reachable

### ISSUE THREAD

**Issue by xrow** [hansode/packer-vagrant-templates#95]
Hi,

I had problems reaching the repositories when starting vagrant. 

´´´
[root@vagrant-centos7 ~]# yum makecache                         
Loaded plugins: fastestmirror

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7.1.1503/x86_64
´´´

I removed the yum release var mentioned in .ks and now it works. 

´´´
# yum
mkdir -p /etc/yum/vars
echo 7.1.1503 > /etc/yum/vars/releasever
´´´

**Comment by hansode** [comment]
It looks not vagrant box issue but centos mirror issue.

+ http://mirrorlist.centos.org/?release=7.0.1406&arch=x86_64&repo=extras&infra=stock
   + => web server responds mirror list.
+ http://mirrorlist.centos.org/?release=7.1.1503&arch=x86_64&repo=extras&infra=stock
   + => web server does not respond mirror list.

Why don't you ask centos mirror site administrator?

**Comment by xrow** [comment]
Will do!

**Comment by xrow** [comment]
CentOS says use "7" all time!

http://bugs.centos.org/view.php?id=8534#c22867

**Comment by hansode** [comment]
Thanks for your sharing.

**Comment by hansode** [comment]
When you use vagrant boxes which I built, I think that the first thing you do is removing `/etc/yum/vars/releasever` file.

Becuase the `releasever` always helps me when I use old CentOS version box.
Though I often investigate old CentOS environments.
So I'm going to create releasever file so far.

**Comment by xrow** [comment]
It is up you how you want to handle it. For now I just did a fork and I just wanted to report problems upstream.

Maybe "cat /etc/redhat-release" can tell you se same as " /etc/yum/vars/releasever"?

**Comment by hansode** [comment]
Not only same as /etc/redhat-release.
My main porpose is following:

via https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Using_Yum_Variables.html

> ```
> $releasever
> You can use this variable to reference the release version of Red Hat Enterprise Linux.
> Yum obtains the value of $releasever from the distroverpkg=value line in the /etc/yum.conf configuration file.
> If there is no such line in /etc/yum.conf, then yum infers the correct value by deriving the version number from the redhat-release package.
> The value of $releasever typically consists of the major release number and the variant of Red Hat Enterprise Linux, for example 6Client, or 6Server.
> ```
