### ISSUE TITLE
kernel-headers

### ISSUE THREAD

**Issue by xrow** [hansode/packer-vagrant-templates#96]
Hi,

vbguest is failing for me. The reason might be that the kernel header are missing. For centos 7 they a in a sperate rpm called "kernel-headers" and not in "kernel-devel". The package "kernel-headers" should be added to kickstarter.

The error:
´´´
Building the VirtualBox Guest Additions kernel modules
The headers for the current running kernel were not found. If the following
module compilation fails then this could be the reason.
The missing package can be probably installed with
yum install kernel-devel-3.10.0-123.el7.x86_64
´´´

**Comment by hansode** [comment]
which centos7 version? 7.1.1503?

**Comment by hansode** [comment]
Are running kernel version and kernel-header version same?

**Comment by xrow** [comment]
Answer to 1: centos 7.1.1503
Answer to 2: kernel-header isn't installed. Question can`t be answered. If the box would install both, they would be of the same version.

**Comment by hansode** [comment]
OK. I'll take a look.

**Comment by hansode** [comment]
Using hansode/centos-7.1.1503-x86_64:

```
[vagrant@vagrant-centos7 ~]$ cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core)
```

```
[vagrant@vagrant-centos7 ~]$ rpm -qa kernel*
kernel-tools-libs-3.10.0-229.el7.x86_64
kernel-headers-3.10.0-229.el7.x86_64
kernel-3.10.0-229.el7.x86_64
kernel-tools-3.10.0-229.el7.x86_64
kernel-devel-3.10.0-229.el7.x86_64
```

The installed kernel-* packages are `3.10.0-229`.
Why are you using `3.10.0-123`?

**Comment by xrow** [comment]
Hi,

good question. I do not know why I am using 3.10.0-123. Maybe it is a false bug report. Please close for now.
